services:
  db:
    image: mysql:8.0.37
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_USER: docker
      MYSQL_PASSWORD: 12345678
      MYSQL_DATABASE: rest_with_spring_boot_erizoka
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - "3308:3308"
    expose:
      - "3308"
    networks:
      - erizoka-network

  rest-with-spring-boot-erizoka:
    image: erizoka/rest-with-springboot-in-java
    restart: always
    build: .
    working_dir: /rest-with-springboot-in-java
    environment:
      TZ: America/Sao_Paulo
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3308/rest_with_spring_boot_erizoka?useTimezone=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345678
      SERVER_PORT: 80
    ports:
      - "80:80"
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - erizoka-network

networks:
  erizoka-network:
    driver: bridge
